name: jwst
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - astropy
  - ipywidgets
  - jupyter
  - pip
  - pip:
    - jwst>=1.20
    - tweakwcs
